version: '3.3'
services:
  health-me-server-ai:
    build: 
      context: .
      dockerfile: local.Dockerfile 
    container_name: health-me-server-ai2
    hostname: health-me-server-ai2
    working_dir: /app
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    tty: true
    networks:
      - server-ai
      
networks:
  server-ai:
    external: false
